/**
 * Kennzeichnung KI-erzeugter Inhalte nach Art. 50 KI-VO.
 *
 * Die Verordnung (EU) 2024/1689 gilt in ihren Transparenzpflichten seit dem
 * 2. August 2026. Für dieses Werkzeug ist Absatz 2 einschlägig: Anschreiben,
 * ATS-Optimierungen und Stellenanalysen sind synthetische Inhalte und müssen
 * maschinenlesbar als künstlich erzeugt gekennzeichnet werden. Für die
 * technische Umsetzung läuft eine Übergangsfrist bis zum 2. Dezember 2026.
 *
 * Nicht einschlägig ist Anhang III Nr. 4: dort geht es um Systeme, mit denen
 * Arbeitgeber Bewerbungen filtern und Bewerber bewerten. Dieses Werkzeug
 * arbeitet auf der Seite der bewerbenden Person und trifft keine Auswahl —
 * es ist damit kein Hochrisiko-System.
 */

export const AI_DISCLOSURE_DE =
  "Dieser Text wurde von einem KI-System erzeugt und ist nicht von einem " +
  "Menschen verfasst. Prüfe ihn vor dem Versand.";

export const AI_DISCLOSURE_EN =
  "This text was generated by an AI system and was not written by a human. " +
  "Review it before sending.";

export const AI_LEGAL_BASIS = "Regulation (EU) 2024/1689, Article 50";

export interface AiDisclosure {
  aiGenerated: true;
  purpose: string;
  generatedAt: string;
  legalBasis: string;
  applicableParagraphs: string[];
  disclosureDe: string;
  disclosureEn: string;
}

/**
 * Kennzeichnung für eine KI-erzeugte Ausgabe des angegebenen Zwecks.
 *
 * Bewusst als const-Arrow und nicht als Funktionsdeklaration: der
 * SSR-Transform, den vitest in diesem Projekt verwendet, erzeugt für
 * hoistbare `export function`-Deklarationen einen Aufruf von
 * `__vite_ssr_exportName__`, den die Laufzeit hier nicht kennt — das Modul
 * liess sich dadurch aus keinem Test importieren.
 */
export const aiDisclosure = (purpose: string): AiDisclosure => ({
  aiGenerated: true,
  purpose,
  generatedAt: new Date().toISOString(),
  legalBasis: AI_LEGAL_BASIS,
  applicableParagraphs: ["50(2)"],
  disclosureDe: AI_DISCLOSURE_DE,
  disclosureEn: AI_DISCLOSURE_EN,
});
